\paragraph{Why Early-Epoch Confidence Variance Identifies Boundary-Critical Samples.} CGR's central claim has two components: (a) high target-confidence variance during early training selects samples that lie near class decision boundaries, and (b) this variance signal reflects data structure rather than stochastic optimization noise. We support each component with both theoretical and empirical arguments.

\emph{(a.1) A theoretical link from variance to intermediate mean confidence.} The per-sample target confidence $\Gamma_e(x_i, y_i) \in [0, 1]$ is bounded, so by the standard variance bound for $[0,1]$-bounded random variables,
$$\sigma^2(x_i, y_i) \;\leq\; \bar\Gamma(x_i, y_i)\,\big(1 - \bar\Gamma(x_i, y_i)\big),$$
with the right-hand side maximized at $\bar\Gamma = 1/2$ and equal to zero at $\bar\Gamma \in \{0, 1\}$. A sample can therefore have high variance only if its mean target confidence is bounded away from both extremes—i.e., its predictions fluctuate around an intermediate value, the softmax-confidence analog of low margin in a classifier. This separation is verified empirically in Figure \ref{fig:Boundary}: sub-figure (b.1) shows that high-variance samples cluster at intermediate $\bar\Gamma \approx 0.5$ while low-variance samples concentrate at $\bar\Gamma \to 1$ or $\bar\Gamma \to 0$, and sub-figure (a) shows that the high-variance samples are also \emph{visually} ambiguous across CIFAR-10 classes (e.g., airplane against featureless background, partially-occluded animal), consistent with their proximity to class decision boundaries.

\emph{(a.2) Connection to margin theory.} The role of training-time margin in generalization is well-established in classical margin-based bounds \citep{bartlett2002rademacher}: classifiers with larger margins on the training data admit tighter generalization guarantees. The bound in (a.1) provides a corresponding per-sample statement: high target-confidence variance forces the model's predictions on the sample toward intermediate target confidence, the per-sample analog of low margin.

\emph{(b.1) Cross-seed reproducibility.} To test whether CGR's variance signal is dominated by stochastic optimization noise, we measured the rank correlation of per-sample variance vectors across the five seeds used for our main results, on Split CIFAR-100 with buffer 1000. The mean Spearman correlation between seed pairs was $\bar\rho = X.XX \pm Y.YY$, well above the chance-level value of $0$ that would obtain if the signal were dominated by stochastic noise. This indicates that the variance ranking is largely reproducible across independent training runs and is therefore substantially data-dependent.

\emph{(b.2) Diagnostic comparison of selection rules.} To test whether CGR's selection identifies boundary-sensitive rather than merely unstable samples, we compare the samples selected by CGR's variance criterion against those selected by alternative rules—random, high-loss, and low-confidence—on Split CIFAR-100 (buffer 1000) after the first task. For each rule, we report in Table !!! (i) the mean target margin $p_{y_\text{true}}(x) - \max_{y' \neq y_\text{true}} p_{y'}(x)$, (ii) the mean number of forgetting events \citep{toneva2018empirical}, and (iii) the mean target confidence on the selected samples. CGR-selected samples have lower mean margins than random samples but higher than low-confidence samples, with intermediate forgetting-event counts—placing CGR's selection in an 'ambiguous middle' distinct from both confident-correct samples and persistent failure cases.

\emph{(b.3) Precedent for early-training importance scores.} \citet{paul2021deep} introduced gradient- and error-norm scores computable at very early training epochs and demonstrated that these scores reliably identify samples whose removal harms generalization. Their results provide precedent for the broader principle on which CGR rests: early-training importance scores can carry meaningful, reproducible information about training samples.

Taken together, (a.1)--(a.3) establish that high confidence variance corresponds to intermediate-confidence, low-margin behavior consistent with boundary sensitivity, and (b.1)--(b.3) provide direct empirical evidence that the signal is reproducible across runs and selects qualitatively different samples than alternative sample rules. We also acknowledge that other sources of instability—such as label noise or severe distribution shift—may induce high variance; we evaluate these cases empirically in Section !!!.
